### ISSUE TITLE
client: allow filtering and creation of parameter groups

### ISSUE THREAD

**Issue by ebshimizu** [ebshimizu/DesignAdjectives#50]
#43 subtask

* [x] active parameter set
* [x] filter inactive params
* [x] allow creation of parameter groups
* [x] limit affect of all interface function to current parameter set (server will need work)
* [x] Snippet ui rework: select which params are affected for training (all, param set, active)
* [x] Sampler: set which params are affected (all or active)
* [x] Snippet: Identify influential params
