### ISSUE TITLE
server: parameter limited operations

### ISSUE THREAD

**Issue by ebshimizu** [ebshimizu/DesignAdjectives#51]
#43 subtask

* [x] Get param info from client, relay automatically to snippet server
* [x] re-write functions to accept a current parameter set and act only on that set of parameters
* [x] refactor client driver to use enums for sio action names
